apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: thg-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thg-web
        tier: frontend
        track: stable
    spec:
      containers:
      - name: thg-web-container
        image: gcr.io/trendinghashtaggraph-189213/thg:v1
        ports:
          - name: http
            containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: REPLACE_OS_VARS
          value: "true"
        - name: PHOENIX_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: thg-secret
              key: phoenix_secret
        - name: TWITTER_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: thg-secret
              key: twitter_consumer_key
        - name: TWITTER_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: thg-secret
              key: twitter_consumer_secret
        - name: TWITTER_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: thg-secret
              key: twitter_access_token
        - name: TWITTER_ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: thg-secret
              key: twitter_access_token_secret